#DEFINE IMAGEM BASE 
FROM python:3.11-rc-alpine3.15

#DEFINE DIRETÓRIO DE TRABALHO
WORKDIR /app

#COPIA ARQUIVO DE DEPENDÊNCIAS
COPY ./requirements.txt ./

#RODA COMANDO PARA INSTALAR DEPENDÊNCIAS
RUN pip install -r ./requirements.txt

#COPIA RESTANTE DOS ARQUIVOS PARA WORKDIR
COPY . .

#EXPÕES PORTA DE TRABALHO DO FLASK
EXPOSE 5000

#EXECUTA COMANDO PARA RODAR APLICAÇÃO, PERMITINDO O ACESSO POR TODOS OS IPs
CMD ["flask", "run", "--host=0.0.0.0"]
